---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgATUWH0uY8g3f8CTo2y2QfVocKAAHDXyUsuAvc21C5+O+bgE2PwEELv5kYDs3QunDRxKqGNTj16Eke3m+NeS/XVXf0y9UMOoaiIBQimXrflu3iXGZo6mFS7+IiqC1zlvBaKcHQ6dBDhj+DsmR52nIdPGUh8TFzAdV4o7moXtTBFXME7Y/3GgS0Bf4KazBGuiuZw93JVf8qYeesMm3BDz/wMQgC3XlrTUqeN2FgI6ZJrV/3OrE4IxpbM4n3hC+u3CGlo7NucjchjCKxb56ESjaH4W+ZDAG4jhbuEz0URzTyt/EyE4pylM5/CDLM31xIe+BbLfjFoOO3scYE/OP0WM93ipIu19FM+xgTKDBol6SOBzK678rCJzAbq0pfm08Z8Unea6sk24JvwT4kt4dOPeQx9oypdITey4MjFC9IYWvhE4Y5XoBP2/vjDkWJ+9hxFFrSFtnPauzeQZHM0R9rs9I713AG/3YKtWivkH16xfwxglgLGtgYyKwc/d8q+fGglMvnjIZ5SlAtgw1RLO/fjZnWTrgVmFmbvJOS8vxsaTKfvWKqfm5SeZICabe4rR8MnmjT3w68lWI8eYWfsONIHLSP4ruCd2UzRllbvWDLcoPW4NBc8OorPaXgEA+MUa9DuyYO7Fb+OmqS0Xq4u8AvyFxNgldJcZySUbda5T+9tUXB5qkQ97moBBsNDa/tFy2PPaMPXcJFUcDMQ1Whm
    userKey: AgBoDW7qcm9GJywACv7HFt5bi0rFt1A/6i8Dy9jkpIBpRH+r5LIZ4cxN4nUmxOaRxaf+EOtfGZt/NHQuEGQVzvXbszXE8l494lCGSyOpBjHbStOZ9Nww5tgLvSzCs3abbsA3HSN5G3sLUYApP1BiTmwyDXrdOxe48G0CF+toxZgb08peKWszJ0TnCgO+VTgyotcqv98z7Th5WDwv6++GGOgCb7v0RMa9TqQLg17gyRY1/7BpNitPu3PLVarcqOUiRy1smKWIHuw6y386kA26PXfFE1bqDFRtRBHotjvxNj7WejcYMpPgT70xvF7xIP7huZ58PYoxnM/UGmR03eX/3vjIPMirnRc4BVBftohHmkMWH6vwt2MyIyvPI/uX4XuKn5+QxcxXF8p3xNKKfyx8E1fmEHvXOjZb/ZF1kOaIabgvVKcGi7I39xqEyjxl4XF8phz4JfkEApxzQ+GsCE9b7hWSb1DPoW2/7GGlOqgn9pCRWFzkhOYnjwGUJgXythVaXc2SNDB4mm74gWLcKrrY0W9W40dsDt7vOGxwN5ilqvSnI9B0n006aL0wExu8cN8u7Stg1qb+ogWgc6Z0b38ptYVdryAZ316OzWJ6H3FWmAuDy3P1wG9ymxugcc7bPfYR2+2A5jrg5J4a2RY89uU2lTn7oZ4Iod6/lvaS0gR6+39WLMpoYRMLogOavf7LWcleUIB5e+TCkkYn+rgl25L0P4Hh3ecsfoPGuUSL4tiVmcFetCBqQWOlwNsJ
  template:
    metadata:
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
    type: Opaque
