apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: talos-homelab
  namespace: argocd
spec:
  description: Talos homelab platform (CNI, networking, secrets, certs)
  sourceRepos:
    - https://github.com/Adithya-Rajendran/homelab-talos.git
    - https://github.com/Adithya-Rajendran/nextcloud-stack-chart.git
    - https://helm.cilium.io
    - https://charts.jetstack.io
    - https://ceph.github.io/csi-charts
    - https://charts.goauthentik.io
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
