---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB5kUbE30oRKhVfpNG09tk1Q+KN8nFDxQlt6uynIYQwLShmNyd3exI+wiKX/9ez7V6rg018VWnAOG7byovPTwkFmbzZtqYfDyv8OdRefpbGfTF6TVoalYZDXIjMfiL6lX9CV5jDzMQSklh1e1BbSoKyWDtD9/wZOw0EqgwnYQLnxPKYI9a/yoFI6mv3HcZ6wJS/TrBgvl8dySkPpLG21axq9Z20l98TRLJG8+Gy356L3Ina0MJFbrP5nq+idYWdb1AtU1utsbdrOeRe8ggs4Vt8cYpy/LogIfqRhgtKXwvK+dTID7+CwMlfTR2w19PVmkdu6i9yo4Yv891ZlpCegMitGHGs0mYf1YincCeqpyYhiP3Qy7c0jXoHkh/7H8ic29C+vWYlgeiuOrstKLIA3/yyoC8bR9R0a3yNOZAlIJMiSYed+CrqSD9WuiAEUm94Q2wRZdF9KJli+60BQ8NEF1+w1BJP0KSYHCa6aJwCAdXWan69TsyAgu5t3zlQ/CHDIPAqYtDFuAibcreLTiHcB4cS86uDAghZGRYP4wL4iAlSRknrdSHD4m3MA+XMbrY7gQZ1b31ifCpo9nflMhIGZYdVGTPX4sbf7JWRqpNomNX8gVqCBq08eTxN7cfCgHseVxHQxTkJhwPVjLN5dvqzUlYJKutuDZBRjJ0iIC4RpvoYpPpCzK4G2QSAbBkfRs+x9L8e2d43UfG8Jpkh242neufh6phwu+N5kqvrox1sJpPTiL7rbVpdV1wOay82N/KVvVIm32j/SA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
