---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql-creds
  namespace: authentik
spec:
  encryptedData:
    password: AgBHV044l1aO4Q7yrSqzOSCDI4+Cc5dGy2hRbFOV0FP0tVvmXNuE2KMU4+U90POToJfhLoD35Vm4KRoJN2o2rKFWYGzqOL81osoTJSAvlmV0oOe2sUDvpTbojiW4Kyi8O+d9jbxUeuPHxFy363kyT8pW21tvTi2JSZjobYUiGqrARCOmmcB5geLn/Cc1Gd/m8NOHF+QO1uxdXdrC1JP9DtXIGUSw12anZONASe+SRosyPh4PYR3bN0V9a+tDPrcoX+c7ny2bN2UkSfUCGzUAM6LkibfYQdrtztVOevZY+ghO5kweam5MiZtMNOkDtb5giciP3kGejmGInP2km0jT+8X5FfH4PcymPn1Y6RVn38tz2iP7Y42mIszp0ivsSWOsexpMgBFa1WfZSvdpTZYCWHcnF96tIGckufhCGNOxUnf++cP4XMadg7qMP5MWP985Ffy+jFqaHXcJ3JWxFeNm5dvmye4xRs14Sctf/xCkpFLtFCLB0ll1KnZjioXCzrIm2v9FM5VgZUCveyypbhjvrWfpIm8nJDkdOhVOnkfyweEtW6hpFNTB3dAieCLbnBz3ApqdMxDTWJykaWBo1k8CpxbkFLddngNCAJZ1aqqM61dxg4XeCTU4YIGqKNw2ZFP1uCWPuXHs6e9xl62hMA1wRyuZRI43ypg9K+Z1aPJl+5MEXgxFqliji9JYiB4KkJiHXALulU9FTi1i2D9hom+DrTr/SH2wZTtvjB7b6J5tq7HgpxKxJeVm0iUVBQv7vYyE9zg=
    postgres-password: AgB4Uuw1a0GGiZXCVEH7sw6TQRgtuPz0Vqw7h+H3+CXTr4GX/aJWYaVwZO27fmioPxEPbBCripi5J2xo6utpJ2ibrL0FEd7UtSygSpuReHvK3V0mmIjPintAVSGr09QQ6Y2IwYTPwB6XC4v69ZUvvyHcNPwHqvsGW++3KdDhASzFH7FPwSqwUR5bEkgh8AcIuUEtM/x5Oo2kGlZWF6qCxsSdQ5FJPWbrcDESEF2ycrcKz4qgzw+SDg+7nh0vr82AlQZnYo/jTVQS6Kk6D9NeEUvtCHNxc/XkqeknVXAl8CNcE2SMgjwdvcWD+m5QsrLLzT+GCavL5vexWXsHD7s9GefQDR4ZWGiWKr436gw61CtCzJaRMX5K4+OLW98bz2co+gjDx3KWR8dbkjm78EtpOwHHEzFejjQwKVtOOzMtj38su492REi7Jem5BKvSo7Ue5xRBnwM7qVx1GPJ0q5SWVFh7x5S9v1gsO863XegLwl/EqC3p1B3qJsvnYMSb4lVcQK3N8zo/6xRzb71NxDBYtDfjsih4+dDLiC6+6ktrZwtoioE8oMKK7huLceNN9uSTnQYbMiHNDD8KNnHOaL2cFOZwMPlWtgctkJe+6QcQ32ZU/ZvVjMLq2lj8KdIx2BsRtniPlEyctEyhSH2xWl8ZUgmiAt6lCufaffWXvanUSs40oYm16m7ZEkNjbypdetw7qu8jZ0bCsosEDXUL
  template:
    metadata:
      name: authentik-postgresql-creds
      namespace: authentik
    type: Opaque
