---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dhi-pull
  namespace: nextcloud
spec:
  encryptedData:
    .dockerconfigjson: AgCeRKonxzALaPGhjFJQdxmTilisNC9bhv7Mk0cGxtwtDOlWMhghRJZAFA/u8qwCRsVTdpewLI1eIXaaVm4OaW3a4A4WSZWfjWz69FfEjCKIZ2dJ5DsyrRJHb20nhznbmI34r+oczyZjjUomobPpDIb2bS5jMfSa0fdsNkOUEtNXMCH4rwHSUkyLdEBqmOPCDPksTknfaOmmrpMurhapY1iRqlsJkfl3A5mBQ1xisUS5lOzmzdP93ZR9kYQ8428i2V2S4+gtvT+nLKWyNgNm7OqZ928rxOXpO9uOM/G4aI4Ee3J7eCQXC2Ci/UxgqJuOu/sBt5bCtbJfZQ88s3ygQ9lFIErBitZ/kTCHyQz+h/1wnEStX6lGOiXQ96xU0Y5RkwMcE1+y9LHCuWUzbLTdA5WEm4HLGPNadF0kiLpAPmAhyEVA+SAcPyPCEo4UghY9ZF6D6fvSVprY1eE2b9vtzFq0xNagqxLzV9oLjbhQlG5UsjyKMwF5uiQjY4pYQSkR8SRq6IcLYOL+76jPrMktHUPGlXTB87alytCR/DQRFVT+ZXQSr0FAZg1FYulzaVGtn5+OeB6nbx9Yi274ISGxqTvIlZSRqC8KZpy/wUpWal/UleX5QQwR2jiL9QbRvYB9ZdF3BgxmEOBUywZ34J0E4TUgm/InQnSO5L6YwhY3Emppp9a1/NHty9OZ624ExG3SHb4soNCzYav/jbbeuXo5XKhGNVhQ9Ifu5eLaSbIgtIjxcWYktGd4QZQmiTtVBVOvBmPdhC+bTzz2X+EXh0/jCtne7KQ3X+eB1YgXZ9x5cA295T0Q6TDJhKeVVykGC09v1+taiEo=
  template:
    metadata:
      name: dhi-pull
      namespace: nextcloud
    type: kubernetes.io/dockerconfigjson
