---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-stack-whiteboard
  namespace: nextcloud
spec:
  encryptedData:
    jwt-secret-key: AgAiMafcv5y3lYQnAutuXwT7aVOvld+pErPiEPjcDpeWuauZZ5q2+i4w1AlP3P9KRiJqrRTRKQ0+65G0fmu4yYSIpQt+KW7USpJVEm4I/ZdwPGvGIOTs8iOpeouq2aR2nHhbf8vs530R19LTgI5Z++XmYOpx5SDqKxTZGw5xlx8bsBdIo5Lr/9+dqBDRQCqtUdkBMo7qDpF9ZCybJSyTVz3csUs6YSQlmNvIHawoGk5fD/MVm6C8D/J15HTBlan0ug/XUBR242/tuQLrO3x+MnJ2bVOjF6fwq5O7kk8FKooUJtdbvzGgS0d8WhogPgplg9YzI77Xc4/kLiNhauBGBdE7W3ZjMu39FbZdlzn+yVmhhzQcRwBS9e9IY6apqxT0/jIhCGpXxBtw2IKxWpqHE+B2+PelZkPqKGDSYcLaasDDUa4B7gSIJ2txM4InAdSk433qC/a7N8DjlZuWdqhjMTDFnI9W4zVkh6sXCV1uiQrJ7neqNDsTxmpV2TpX5zMNKhAQcg/a/Kn/99J23G9quk0aRadbAGuY5tLORQ89/0dlRuYPyxkNNRUjkm8l7OlMk74jNgSl9eUysK5c8K0X7FSrzZnAGA1FBtzwdHz8FxdLKvAWSHZRcKApqvdG5suQZE4v57x46hzVNsqH4PG6UR/1bKHG9Yzi/sdo97dAOiyvjGjr+uWyQ3wAgYsBjokToldswaptRoXMO0OEW+exO5Do4MBh7vl5CSpNhkMhcZDsLEVtwt4n1MiSg7/+BrblvkM=
    redis-url: AgB8I1PVLVGsAtTxN8DuH4dcF3nK7wFCqA3gjPsYTTvlYpnLYw0BHzeP4Gzc7EACc+tADr1wyKaoF4HnZyO5U0Xnh9HBuWttrPv10nteAG+GvXEi0DbbrZXhFIWq8XzwWgSYSWb3IjuhODhCcnpubm4+v7P6Dc+4Yadw/CGWhxddUpAY1sUh7OxPEUiSgPq5gm+4ztm2IYupdwEnthnbTadHU32jDTq/WJtb1fYXAZyYcM4KYb8lTyfv7jMLdwu46I+gcEw6H8i8gyUNl7alZurK6UhzdvV4fW5/24xi+FJI5e5C1q+jja0a4DXP2bm+LSjaD34/zbfRZcNjxg3Gvh/GzkUL6Gv77yDEDLSNZyxrjgRGP1P2+f9Wo7tK7JHw2VnJS3vvDdJjzr5wZ1Dopr9bryYkVLxd/v0lbi/SVDRmqngTtTFN84rNyvKPIUnqQ9YNHbi2H0yBBVU/VkcCJaXIaLYSYhJJPo7gdAlgFvljJwNwFI6rmmbSpK/eQHBj7WJEOQqM10FW7VtFZDOqYyZ1lXDvgnlRCWYwhXgY38ByQey/LObHxJ3O3vGaePqcwu7WAl9NZ/WWi/CbhkD2aMEnbbGeFOXU67TMXbBmbhYaPB+1vw+5T6nCbguufRGZCf+PC2FwaxeodCzI3EZjBwS+Snmj40rSiaVYGcC9dlIPyAtIwDd9SskXhVxhlZWjJNY2hTmE6RP3SnP4qHBjvZQpe2DhffUMZ62TbT1xz/61yN1ZYGWU/S+E6j/78aphX3xYhJEDt19piIW/h7mncBudJNCbKfDF7Q==
  template:
    metadata:
      name: nextcloud-stack-whiteboard
      namespace: nextcloud
    type: Opaque
