---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-stack-admin
  namespace: nextcloud
spec:
  encryptedData:
    admin-password: AgCeqV2+DwwgiWJG0XkhD/mzMfVXGx0zmvPNuCOVtguiBmWReMw77KpeRvWLJMiXkhbfoA/Ekv+W2ijL7K2/m/4Bmx6pP9MudblPOXl9ZmJ/zsXT4rTyuDlED1T8lTh2uhnfyyMsvxjBQCaO13bnQ5wmRkArZ+slLu/j6qer1sTB5SZdVZJVpXIwmuus64Oywc+JDY8lhRkMycq94tVyTcfTDKxXz8Hh+6ODHouOwrJITCL17QKpO4fozi469FccJOBo9/zrToUD1zRbiAB+czCM9mTHz2IN7rXWZIcv6fgunfP5//OoyibxfkMRkZjOAGaK/F++btmDdQZwIBIXoCavkvDf2cCAzsgCGJfHV+vXN/IibaMgtA8A/qjKjjAf1ARqU/qOoQ/+j6m1CA+4H8cJ4Fq+JeujkCsxnK8NlNIF/gPQpxnNXrY/1DRCwqLFC4kbFZ5RisiI4DSyU/049b0feYAaoAuk8GN6Gishn8QsRcxE5M/WgLuOqXlp58xHWeFx0uAWTyV88lWzzxpkOXko+fOiv+tGcsz0nc/3WFbUeInPQonzhT0TKvFbZ1hEyedgrMAq8K1mYFoFHfWATcNpb9ccb/ij/oW8KohbL6uhIzgP0wnwvdiWEbyjFvYxInLV6dcRG5klW/5QH0Sd+8IBTUhy8mi/W5Uw7cl96wK0Hy2jS2fBy1QTAP4ToRcCzBXtWb+0CKz0ZrMqrQP4uP1+WddfiONq3SKbQJDxmhSm1w==
    admin-user: AgA56bD/9eFPNivdk1glt6fZrXDmXAWcf0ZwxDn/4E/pWOE8+i+4UUWigGE/CQYGgGxmEQq70YomcUnlMX2s5Rl6tqIHW7k2VTaLXLBkOQQNiYqBPGGUhBW1km57mCZJ9NTZT5eg0DZ07/sek+kNj6PPPWWQETfu/h5M6GBwaa5IMoVK1pC06nCHLALFM6JYw7BYmMNnLFEk9fUeaqwoe6kg/A01IQVP6z6C5SEH9CeYc2YHP2d774K7rNw1yTPI96lZU+W30uOYk3R9MTjF0tkv80DbdZtj1rpZ9r48GB+8vBBdO0QZUTICzVQMh4evlgJlUV6eKvwIDqPV9RiBmK2B6pLtjQpNAkpw2TGRnzn1YpeVtyUvx7oB2lyIU4kUEcWwcS8mFBg4zvCnzdF6KBZgRGwYSdwTiYCIFRYu2HQmQjd8qDwsPpYWe1+sPKi1SL9WS2YfdPdOHD8UY8MFtv+jSaYVzxTxcFFGt4w4DuK8mJfNLRQi4u7IR3rYjEI5A11eUc7gerpGqSzdvQtVh66D2eU1WT4Thfclcn3uCE6I8m66NqIS3Cc75FlpiCrKtWnGWSsXxExk7Mkovk4OiMDV4MEBEWHRCYTcByIk+NlV2g8zaHOqVqnAKF4hg1LhWqaR2Khi3YZq00PVyC3Z7RtGOFXUz2zbTeVHuwaWemNejSQu2OTC2o/mf4vN1oqiKEvOLtK1vw==
  template:
    metadata:
      name: nextcloud-stack-admin
      namespace: nextcloud
    type: Opaque
