---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-stack-metrics
  namespace: nextcloud
spec:
  encryptedData:
    token: AgBJnivGGmqxG49J7/SBwHPI5QMjFes48m+P7ngPe72eEROLJmepq7xpbB67uTAGGxEDj68Djf99Il7hkEJLuxPVyqnGt8fXnUn0AT5RN/gWGj6q6RQNVTkHUK+F+ws0y7DafcWXcKOcebY5uR2iU/BC1oL7pQXsUYyt/k5lnDGPQNbgkgP/H3G6EKdq4CBj8lLpk31/9E8GwM6v7Wo4vxCvDyTJoRHxiE5GOdOvogNdqQu9yKyrKAwgqM0GHMpHEjICM/iILYslfgVbMvpNxIg9l+1C//num+9jygLFpi9uYWBwb7hNPSVX48DbsVyWBfB3hsb8GeHHCNt0251Qy1a1qOOHTcLVpa2QwV3rjk6K6HEya2JMnbsZq/SLIijkQ4ub+p4QFE/z8haVB3b6jDujDTmx0QVjzW0Y1mfi283DVaLVWZU17NszC1LDom+gCoUYMtsIXDqYsdLxcLvenSoTbtxjIVXEymnR7cFf5Xphzyv96vKBC2PWSr2NTGG2CBBsDtH66aGAxh6+GEEBHf0QuvwACQHJTxWH8rPfYnbd1YrreCCcF+NOY8gzFBy/dbQ4/I+vonOolqK+uSM/T0kaTQ9BWGcwH5suv8MWsdiIjdsNxpg+qmWBSwsILlUw5PVmuebW635kdl0u1ELk+emP09kvhSCF7GCh7DGKkBzA7zWvsg/mPTNehlGKLXqIHDs5NWqrsTWOc5awXIfo4Z73hYe8W7LmYk34OfptbXozIsjpHj7EesnA7GsGlGvWKpw=
  template:
    metadata:
      name: nextcloud-stack-metrics
      namespace: nextcloud
    type: Opaque
