---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-stack-postgres
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-db-password: AgCzbaEjQGT7+Mm7EQamzrakH/iBe7usztZrcQnvAP1xFwkT42bmS8jZIETvQIhGiuGoPIx6jvQL+cqsBKiAXUuiKw6XVNFtjRcm7Tnx63nP+nuXq1EchBkf3TCLepdAqRgjdQtYehFSLeNZUkZtr70nEvERlldPbOuapTzRRmy+1S7tOACf9QnWiqzHecPf7MmtueQeUaVK7gcxOTGPhNdk082oxJyzs98+FNjA2LUxKPFw0K66EAZIuTQLiZde0IZV9OvfyiHspwWWYWNjMyK2YNQ1AYphThXFbBrlmNfRTix5HDCMHSfiaFNGfYSihK0FcYJ5tyqVA1ymDhmERupstTrus7SbHA6WTtvNihK/5TfoSmg6a4tvsoWYgffbdwH/BzKLrNLVLXD5GO5SSupds2droKIrrHrnv4zZq+qjoB69Nxcy2gKurEDoX0sbZ9vfTTAob4cLRjT1TlbeKLQV+yuNRdYdJg8yVmpLu0OtZBrmmnIGCIyqnr93R5kjtwu7SjYXHevIZDiEkeBETZqf+MI0ZDMW84r3ejKKQvGcXro+3RxWCJ29UfODwaqyLi9CxG5j8/Qa37xYloZ2Z67PvUWiGuqZdDaCc5dPO82P5KRg5RkD7s+AjzJbTNHXQ3OydvI7s5im3n1kx/wy90DJ2KtJhaYluluvan2RD8KAnrJfb4qWuAue7d9hba/1sF2IlSIr2HmoKudwn+6L8cNIBVDDVArS54E3DzCHxEFvuA==
    postgres-admin-password: AgCxvAGUmRjHCuJLZaaVMQnkZ1J1kCkEtQ8u0aVDmeHqZQE27N2nTcgqR8411uaOGpfOsI9WPV7YXT9LEF0FhIbdIChNB+rp+NpTmlMXfjH8Dozs0mV/rUMPYq7nSOzSbW9cQxNGShaTaCke4EctWDSVKM71Bc/LyUr872m7qDN4ct59NCe4As9ZsUVh4LpW46dt0yPNfC5CmIBtFA9KzF0Oc/PtUJD8Lh35s4UfI074OqUKbzPqInQ/mM2DYWYGKIFYC76IJiJ1aKhsmqJJMKtovX6yiwgtSfs1xygDeDF6SKPsoKsJeY8Ofu4h5jh5vxtZuzc3kM1BHPY90omzWgFBzE7D4CXEv0FvKoJgIZVNZIoowhHiB4RaztJvbdAV+xhQjUbYgNvtr6kTIeq8/rIk1HVAjIJ3WI6o1o87Ux9TnFzDIMwnM0YYgDcgSmwvLv4jzFPswVH1p92McIH0iMuqMuu4uv/PAnudWOMlB6A4B3iFv0k8j8ckUGiqvwwvgESSAbnvi4v/GcjNgy3v2I43cn3OGYjVeJ8GXGmrtQkFWumGfS0EL9aG6jpK01why3LuJJQdIIx2y0eFn6a+A7cYkhR30NngZ3TszkOI9eApFORNSgLRgHLiFq0KsAspOlB7GeLY1lYc6I13et7TV62hxHlP+gLcpQQ5BOUs2e02d+IOOFizM9pUnJ+D3MnyhIpncIq958svwnhRF8kT0hVkpWIOtqslo2q7dxl8MZQVpQ==
  template:
    metadata:
      name: nextcloud-stack-postgres
      namespace: nextcloud
    type: Opaque
