---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-stack-sso
  namespace: nextcloud
spec:
  encryptedData:
    client-id: AgBIpDWm8WLb1D/5XGePDJ9eGojezeFlNW00nbrIkmVJK4qfLwLUaVJiosloCxxJBuBBFFHg2tMPkLLKHbsToya0yTVdIhqxKp12FmAf5B0PZaxFiQq7DynbsNBvmrdekz367/qZ+N+hLZ/ejYxR0J6oly0GmOCEZQzK8QPUnaTySeESt0J3iNJaoVpwX20arqPxu11+v/IFHocLmm+zLeHlCwRIVTFjo6ByuW7O3BBvO50XEspbCkt+MR6BPA93JT0rl0LvVZNUxyrpKdrjDpxjrxHl+YCICyH63SRbcy08JS374cnbEBQr34lbc6DtmzXQ7QtCjvKtNaLb5YUPVnwPFV6UXe4DcmfhxdryLolXtsEHn+wfrUoBNGMy6oa7TjAS5MU5apVYKQJI5I9gYc6wHchELOyYYRAuge3i9xzj/cBuu8xs4r2NZwMREwW5C7O7KFrgSVYoDtF5WrSU66q4+E2dCyvz9w9G/GuM+xv0/vOw/DeW0ROfGrd36+5v5Hn29mSagNuXFAU+7KDxwrnG62LyChWXaJ4JgEefWMe44rcgEWXDKVRPrb58O0yf5x1vUmfVFNtDJGxZxNt4kTLijzUMjniVD6I4qm1tXcrJNq/bdeRdYuvntwE0k3zCaufymAgecBn7uyy1MVry8+P3nmup0htTs0dnLchrVu+JY3LHw12/icLDk2+vquCTQdYsHW2xItQ2QGA=
    client-secret: AgBD2bVVYyBlgzLtp2AJZgbHVrh0u/92oiLdCSt1G5Mr2FeUgwCdqDUdjE4N3EA8catPLMpv15gT7GYtmB9AswKkzA0TNqV5i9KQYOCjvAIthFGOSzaJa/Qzv8Wm6nBSKJA/eo0KtCQvN9fweCsWdgMYB675Xlq5egHTFo4kVRt8mzGIK3DmIgg9BBUT6jjYXJicCvBM04lla5O46UcVOhU9EEM5BpdO+SslzWb/ly+cIHtwsBd0CZmINJafeRLbZ37YHnqWeKKAu8E1xYfYE/NyKbGcONmLmc4oGCsCsCnI8xiuB2wWa6gFWRcnbdDyGzL3dnosPqpxj5/IecTYyB+FOuFkSAFrl5tq3RAB4BhKBn9t+uhC6vIHFFp1PczcuL2+Y2hX/NEwjBFOc74TtKnUQJYoYVbiTfINE93cPtfNOOlqB8XL2lGDKTakP5cMm4DFXr4H3mnWifL/sosCIrc1vxIdsUpIi8XextbP7rRnvBM98UJJ0Y2rGxmcBOInxtOduMNa+Tn+ON/CUs41IF2cBaFZLtkbUJE6Ix5Zht+ihF6hn2CQyKbCZeaCFMxj+J/jugho0NziL5wdB4WZ52nGfJO9u9OZ4sVzKtTUATGHAvKhRgdJya6GVeBrrtLW8rv4tM8DHxXOz4KD96Z3IbeJQUoG5HyATP7eLecwok6ImX4TTuT3QDztiZ6B5SgavJkaQWLhUuB2EXv3inV7pWX9DsGBXrp0YITt8MLbRkJbr/IbNsWExnzKMZBRVrmcBzkI3Oq15vGjXKtjlJVkdEnt
  template:
    metadata:
      name: nextcloud-stack-sso
      namespace: nextcloud
    type: Opaque
