---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-stack-admin
  namespace: nextcloud
spec:
  encryptedData:
    admin-password: AgB+L4d4UaCdvrjIqRlyg8bou922Xt4tl+0tZF6FTThwEGZdFt/whts0BLOrY9DxtBr/0DNaH0CHnpTgk0Ec2TVy5morWKAz8shkk/tHFjh3FjFO1P3vgpRKpkVa9PNotrcgMtnghIdZCOBKBsjHtTb7oBYOhZXcr+WKDwWet8rT8KPMxNILFH9KtOdE2UdGUxLhteWfzJJvdjcH2I4a9YoSjVlRb+R35KziJ2ibF/pEYRAX/9v6LCAsRe4pFEjQavJIRJJd2adFHrOybLGcAX+wF7naUDuTfQo+FsJiLql8N9m9y1NCm5CR3NXiXBhTeiK3sJnWVc3xHNTY1cC5UkcTmRtUInd/o5H431wUL+vhwY1i0OdTTMU/4DEu8f5m/S6bGqnjvv1tx9lRwlB3gd64mryPViovkGqotioNvrIjjGyItw9P5cVY9Ho1CNUlZjpBbtsHW1OeQIgFAHsYyECv58Ubw6t9XiStT9DTlp6sJGQp0/AQjCYn3R66IF8n5SgpQDX5poyoBjou7XYc7bIlWIJ4C99BnzP0oSC4rSkxT3O3G+sZSogF7wrzZN3oghdlGXwi+kNqLTrvfOVtEdAhiedbjfbMH+jZdF7INKwdTcn4ttpNEMEEDASmXjEEoXhTGMtZltzGRgCYYBl5zrN2Qqhnb/L1OforT5H/IaWs/PKQVUKFck/aycqkp7Gn/UqOpycuDOkgaQq4wEVfap/ycjJV9lbfRxH1PJx8MD+scQ==
    admin-user: AgBSWHy8Np6FQnWf2gFePlpGLoFW/aCCf5SFKUvgmVSowauSg/OyZSvD6drw1W5ZsLz6dwfNsjQWnrpVxMatCmMdoiIQ9/vNjIUwxa/iede2ScjQSRldMopzVLihNWRAopdqCOMmo767dE16glLpqoTBsItwc6N5dZr31yK9amxDRMMgxtHrhPgzKVesfGjHRN9SxNLqHWZ9DXIXcW279i/NzAxphvf5FNdP1lpM5Znw4pbRXY9jwwinmX9fyB4O7l47pg2UnTPgl0m6lVAiYwrUo241x0l10H7qOrjwNygLoTQi012hQlG6r3T7BOSglWv6fX4NpJoMRpFYomL4g6kU5+7vXwcSRwMmyyx6enx3Rsay+6gpXdniOnyIjhHyaB7vHEyL2bbFGwZlPkiaszNmtaS7bThKd1imB7+fW4jg/d66h5stvZ+N+uXy8OlmwKfOYtSQP/TtahsTTulI/Sg0Yg5KCR+NNL64EBecLb376PUn5wR4XR4nXV2eD+ZBlDU9TMUFASa/TPBRzjV+UdJDDy8cyrzyqh4CZgiCoklVLWL+w/MUUSn84wvw6uwCpB9gisjJX3/I4c+mG/WBPA0AHjC6bQH98SI8gB/V9PN+OZDA8GyyY82fT15ruXCaDkAePBaBgWyF3JgytSY647SvC7hbKHoElc3/XVAQzbnGLvsgrd8UCEgqe38Osoz8V6hVU8Wt2w==
  template:
    metadata:
      name: nextcloud-stack-admin
      namespace: nextcloud
    type: Opaque
