---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-stack-postgres
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-db-password: AgA/TNv4CEaL/nIVBnI3aQN0aYun64+pOoFJoufU9undrKRJFdCTqbgGQOIkIfSsienGM9QhFqkjQ888g37Gx3vzJt2osjZ4rwQrhvk8qdJaA5fptTVMmX3e6Zv/2k5+uYAxQqyNBiDIlkWnM2byS7D0NOwqHUHRPDUN3e4cimbDZiQ29OoZSeFh4QC5xUgxbLjFvvLsVyVHylZazaj8QVj504Zb6XC4ilRD+JHtwQnrimrYD2lidlwWbB2sNzxIjURJ4Mh6mzpSXNYS9LvnfxNi7jhDNK4AyV6vHlBlAjpfPy2eYY08r195mLDuoTgJns8rX2ayVl11ms3z8vYvpJ5WaHddkQlT4ngM+FUbdJVmwHlEm4NCcnanUkX8qlYvACqwvB+pN3GtpWuUo1kcl0A7aNAZqpuxOEHgTF7m+eJViOAJpw7bB0lEYSqVDnw8R70AsbDD4zNO3o+oOpa9nIG1JrqVdI+Lluv06xVVG5WByA6XCx1NoahZ9Q3PFAE9EjJFgWCFE7jMyBQ9S1sCGsKo+eZRtvJZiD/r7LMXxf4TbfSU5MU3IoQNclffbw/coiZVZSEyyZTWo6LBRX1YJdZifuhB36vmwNE6tSbFsI+X+l+NC9tQW9UtlxynPe4WDZzcWodRs/7kfyL4tnbqzC6XsxMcjk0IbyFeU89zisXhQ+m8gOda1OeCsYj4zvBRnPp2PVvd9WtB+UBmhYSO0LH6UFZV1RIyZz6Z4ra3+J8vOA==
    postgres-admin-password: AgALSf7apNkUB0WdwQ1UpVsqoiMePoaZfo9W92dwUv3e0Zn2hoiDPOawTR6pBftwSmoB4VpSXI43Iwn0mDQ7GX2NGH+rYJLOf/YrZGZpGPtj8QfjyJLZ23Ztx3Rn15sorMHMKkCp41SvANaT6KjDIO5wpnjddeaBUo+Tp0xtZwUrVeifi6o9zBGC4O7PriVm3e80BtNjQ9ML9EWP2sMrzrd97xoucUgOuA8mrVAJgEqooxRGWhx2qENddv4a+0DuifCfF4SnPKOW42kHoOj/k1SXPk1xHifZZBN4a1KkLreS5a4VQy8MA/ZvdQ80cLcVueQNd7OLLCFq5Hqj4yxN+VIj5ZGik1ulgCZ5adv0uqO4kEU2idGa6V5iO/b/gz4FvZ/nuBl5tsLGMO4Yi8KrC69wXnTfWou//1j9YFMVk2RT1ac2GhDjWo9cmvstWFbOfcNJNTU2vScuiojlxFnaa8Gx4PhBrbndxqlniJrd8KMDRcQZDneS/yTIwU6KxQUPTFSzYBWIhI4doUJ8cs5hSXzg6OLRj4Ohnu/WMpzS92hBIs8Gz49SpziUvZtQwlFPLaiM60kbz/1uIntD/ZoWL2FI3trlRlE3dWBibug+Ur9WFYy3SqYMcoCTpPWPh3A/GwnecH8ciSE8w7AJAc/14+sRxIWDxnRmPDCSxqCqLXq5wReN13GWZlYneUm+bLhiWzaA5pxvG8cwHBlpxyVu4wl41o8JlXV0kYwWzSe+TPRYOg==
  template:
    metadata:
      name: nextcloud-stack-postgres
      namespace: nextcloud
    type: Opaque
